# Generated by Django 4.2.4 on 2023-08-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.TextField(),
        ),
    ]
