# Generated by Django 4.2.4 on 2023-08-31 08:02

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
