# Generated by Django 4.2.4 on 2023-09-07 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0009_room_player_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='score',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boards.room')),
            ],
        ),
    ]
