# Generated by Django 4.2.4 on 2023-09-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_remove_room_score_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='player_id',
            new_name='player',
        ),
    ]
