# Generated by Django 4.2.4 on 2023-09-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_rename_room_id_score_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.room'),
        ),
    ]
